a=int(input("introduce nº a: "))
b=int(input("introduce nº b: "))
c=int(input("introduce nº c: "))
d=int(input("introduce nº d: "))
e=int(input("introduce nº e: "))
f=int(input("introduce nº f: "))
x=((c*e)-(f*b))/((a*e)-(d*b))
y=((a*f)-(d*c))/(a*e)-d*b))
print("La solución del sistema es x= ",x,"y= ",y)

